### ISSUE TITLE
通信エラーのリトライについて

### ISSUE THREAD

**Issue by kacchan6** [geolonia/japanese-addresses-v2#3]
現在`run:04_make_chiban`を`node:22`のコンテナで実行していますが、コンテナ環境、ローカル環境に限らず不定期に通信エラーが発生します。

```
TypeError: fetch failed
    at fetch (/japanese-addresses-v2/node_modules/undici/index.js:112:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async getCkanPackageById (/japanese-addresses-v2/src/lib/ckan.ts:87:17)
    at async getAndStreamCSVDataForId (/japanese-addresses-v2/src/lib/ckan.ts:133:15)
    at async <anonymous> (/japanese-addresses-v2/src/lib/ckan_data/index.ts:43:24)
    at async pumpToNode (node:internal/streams/pipeline:134:22) {
  [cause]: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (/japanese-addresses-v2/node_modules/undici/lib/core/connect.js:190:24)
      at /japanese-addresses-v2/node_modules/undici/lib/core/connect.js:133:46
      at Immediate._onImmediate (/japanese-addresses-v2/node_modules/undici/lib/core/connect.js:174:9)
      at process.processImmediate (node:internal/timers:491:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```

これ自体は仕方がないのを十分に理解しておりますが、その度に3000近いタスクを最初から実行する事に無理を感じております。
途中から継続する方法等はございませんか。

**Comment by keichan34** [comment]
ありがとうございます！
このissue自体は通信エラーのリトライのために保持しますが、別途 #4 を作りました。
ビルド済みのデータは今のところアーカイブ形式の提供はありませんが、検討させてください。
